name: Build Linux & Android Releases
run-name: Build & Release`linux` and `android` Releases

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  linux-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
    
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - name: Setup Linux deps
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev

      - name: Setup Additional deps
        run: |
          sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          sudo apt install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad
          tree /usr/lib/
    
      - name: Build Android Release
        run: |
          flutter clean
          flutter build apk --release --split-per-abi --split-debug-info --obfuscate
      
      - name: Build Linux Release
        run: |
          flutter build linux --release --split-debug-info --obfuscate

      - name: Zip Linux Release
        run: |
          cd build/linux/x64/release/bundle/
          zip -r ../${{ github.event.repository.name }}_lin64.zip ./
      
      - uses: ncipollo/release-action@v1
        with:
          name: Test Releases
          artifacts: your_project_name/build/app/outputs/flutter-apk/*.apk, build/linux/x64/release/${{ github.event.repository.name }}_lin64.zip
          
          allowUpdates: true
          makeLatest: true
